---
DEFAULT_BRANCH: main
ENABLE:
  - CREDENTIALS
  - JSON
  - MARKDOWN
  - PYTHON
  - SPELL
  - YAML
ENABLE_LINTERS:
  - REPOSITORY_SECRETLINT
DISABLE_LINTERS:
  - PYTHON_BANDIT
  - PYTHON_FLAKE8
  - PYTHON_MYPY
  - PYTHON_PYLINT
  - PYTHON_PYRIGHT
  - PYTHON_RUFF
  - SPELL_CSPELL
  - SPELL_LYCHEE
  - SPELL_PROSELINT
PRINT_ALPACA: false
JSON_JSONLINT_FILTER_REGEX_EXCLUDE: "CMakePresets.json"
PYTHON_BANDIT_FILTER_REGEX_EXCLUDE: commit
FLAVOR_SUGGESTIONS: false
SHOW_ELAPSED_TIME: true
SHOW_SKIPPED_LINTERS: false
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: "(\\.github)" # megalinter reusable workflow has no permission to change workflow files
YAML_PRETTIER_FILTER_REGEX_EXCLUDE: "(\\.github)" # megalinter reusable workflow has no permission to change workflow files
