name: Package Creation After Merge

on:
  push:
    branches:
      - main  # This triggers the job when a PR is merged into main


jobs:
  build-and-package:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Conan
      run: |
        pip install conan

    - name: Run build script
        run: |
          REM This script builds the project
          REM It creates the 'output' folder containing end states
          REM It also collects the existing 'build' folder from the repo
          call build_project.bat


    
    - name: Create Conan package
        run: |
          REM Package the 'build' and 'output' folders into a Conan package
          conan create . --name=IWTestAutomation --version=1.0

